options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-west1

steps:
  # Build & push backend (Dockerfile lives in job-tracker/)
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','gcr.io/$PROJECT_ID/job-tracker-backend:$BUILD_ID','-f','job-tracker/Dockerfile','job-tracker']
  - name: gcr.io/cloud-builders/docker
    args: ['push','gcr.io/$PROJECT_ID/job-tracker-backend:$BUILD_ID']

  # Deploy backend
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      'run','deploy','job-tracker-backend',
      '--image','gcr.io/$PROJECT_ID/job-tracker-backend:$BUILD_ID',
      '--region','${_REGION}',
      '--platform','managed',
      '--allow-unauthenticated',
      '--port','8080',
      '--memory','1Gi',
      '--cpu','1',
      '--max-instances','10',
      '--timeout','180s'
    ]

  # Capture backend URL (used to inject into Vite build)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run services describe job-tracker-backend --region ${_REGION} --platform managed --format='value(status.url)' > /workspace/BACKEND_URL.txt
        echo "Backend URL: $(cat /workspace/BACKEND_URL.txt)"

  # --- NEW: Build frontend with Node (clear Vite/TS logs here) ---
  - name: node:18
    dir: job-tracker
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Installing deps..."
        npm ci
        echo "Building Vite app with envs..."
        export VITE_PARSE_API_URL=$(cat /workspace/BACKEND_URL.txt)
        export VITE_SUPABASE_URL='https://dwnhvygjvfpoccbiktxu.supabase.co'
        export VITE_SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3bmh2eWdqdmZwb2NjYmlrdHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjY1OTYsImV4cCI6MjA3NDEwMjU5Nn0.LkHSj_HTPs6Jr_Zo5r8p1e-x-QZn1dFBsWRl7jfp88k'
        npm run build
        ls -lah dist || true

  # Build & push frontend image (Nginx only, copy the built dist/)
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t','gcr.io/$PROJECT_ID/job-tracker-frontend:$BUILD_ID',
        '-f','job-tracker/Dockerfile.frontend',
        '.'  # IMPORTANT: root context so Dockerfile can COPY job-tracker/dist
      ]

  - name: gcr.io/cloud-builders/docker
    args: ['push','gcr.io/$PROJECT_ID/job-tracker-frontend:$BUILD_ID']

  # Deploy frontend (SPA on Cloud Run)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      'run','deploy','job-tracker-frontend',
      '--image','gcr.io/$PROJECT_ID/job-tracker-frontend:$BUILD_ID',
      '--region','${_REGION}',
      '--platform','managed',
      '--allow-unauthenticated',
      '--port','8080',
      '--memory','512Mi',
      '--max-instances','10'
    ]

images:
  - gcr.io/$PROJECT_ID/job-tracker-backend:$BUILD_ID
  - gcr.io/$PROJECT_ID/job-tracker-frontend:$BUILD_ID
