steps:
  # Build and push backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/job-tracker-backend:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/job-tracker-backend:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'job-tracker-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/job-tracker-backend:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

  # Build frontend
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd job-tracker
        npm ci
        npm run build

  # Deploy frontend to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d job-tracker/dist/ gs://$PROJECT_ID-job-tracker-frontend/
        gsutil web set -m index.html -e index.html gs://$PROJECT_ID-job-tracker-frontend/

images:
  - 'gcr.io/$PROJECT_ID/job-tracker-backend:$COMMIT_SHA'
